### ISSUE TITLE
Probability maps instead of Binary maps

### ISSUE THREAD

**Issue by saeedizadi** [bodokaiser/piwise#6]
Hello, 
In the evaluation phase, your code outpus binary segmentation maps (for a binary segmentation task), while there cases in which a the real-value probability map is desired. How can I change your code to get the probability map? 

Thanks
Saeed

**Comment by bodokaiser** [comment]
Hey Saeed,

Check [this line here](https://github.com/bodokaiser/piwise/blob/master/main.py#L85).

You find the probability map of the `i`-th image of the `j`-th class with `outputs[i].cpu()[j].data`. However as with ~21 different classes this is far more difficult to visualize (that's why I use `ouputs[i].cpu().max(0)[1].data` to get the class with the highest probability for each pixel).

Hope that helps.

**Comment by saeedizadi** [comment]
Thanks for the kind reply :)
